### ISSUE TITLE
no star

### ISSUE THREAD

**Issue by 310133239** [ArnaudValensi/node-jsencrypt#1]
I intend to use your library, but find that there is no star.

**Comment by ArnaudValensi** [comment]
Well, this is just the code copy-pasted of https://github.com/travist/jsencrypt and adapted to work with node. We use it in production at https://www.forestadmin.com/

**Comment by 310133239** [comment]
Use your library and run normally. Thank you for your library.

**Comment by ArnaudValensi** [comment]
Nice.
