### ISSUE TITLE
error in key length

### ISSUE THREAD

**Issue by rachmanmarjianto** [ArnaudValensi/node-jsencrypt#2]
var nodeJsencrypt = require("node-jsencrypt")
var jsencrypt = new nodeJsencrypt({default_key_size: 2056});

jsencrypt.setPublicKey(jsencrypt.getPublicKey());
var cipherText = jsencrypt.encrypt('hallo');
console.log(cipherText);

jsencrypt.setPrivateKey(jsencrypt.getPrivateKey());
var uncrypted = jsencrypt.decrypt(cipherText);
console.log(uncrypted);

can you please try to run that code? its error. Can anyone help me please ...

**Comment by rachmanmarjianto** [comment]
upss...the key size should be 2048. But it still gives me error

**Comment by rachmanmarjianto** [comment]
I have already solve it by installing the depencies manually. Maybe that is the way that one should do. Sorry, I'm very new with node js. Thanks for providing this library. cheers....

**Comment by ArnaudValensi** [comment]
I'm glad it works for you :)
